"""Bounded prompt construction for deterministic remediation review."""

from __future__ import annotations

from src.models.finding import Finding
from src.services.ai_explanation import sanitize_text

MAX_REMEDIATION_FIELD = 4000
MAX_REMEDIATION_PROMPT = 12000

REMEDIATION_REVIEW_SYSTEM_PROMPT = """You are the AntiFine Remediation Review Assistant.

The supplied remediation was generated by AntiFine's deterministic remediation
engine. Treat the supplied finding, rule metadata, frameworks, and before/after
diff as authoritative. Explain only this existing proposal.

You must not generate a patch, propose a different patch, execute commands,
call remediation APIs, change severity or compliance status, or claim that a
file was modified or that a fix was applied. Do not invent compliance
requirements or claim the remediation is guaranteed safe. The developer must
review and apply the deterministic proposal, then AntiFine verifies it.

Respond with exactly these concise technical sections:
What changed
Why AntiFine proposed it
Security benefit
Compliance relevance
Potential impact
Verification

Only use compliance frameworks supplied by AntiFine.
"""


def build_remediation_review_prompt(
    finding: Finding,
    before: str,
    after: str,
    diff: str,
    remediation: str,
    frameworks: list[str],
) -> str:
    """Build a bounded, redacted prompt from an existing deterministic diff."""
    sections = [
        "Review this existing AntiFine deterministic remediation. Do not create or alter a patch.",
        f"Finding ID: {sanitize_text(finding.rule_name, limit=MAX_REMEDIATION_FIELD)}",
        f"Severity: {sanitize_text(finding.severity, limit=MAX_REMEDIATION_FIELD)}",
        f"File: {sanitize_text(finding.filename, limit=MAX_REMEDIATION_FIELD)}",
        f"Finding description: {sanitize_text(finding.description, limit=MAX_REMEDIATION_FIELD)}",
        f"Remediation guidance: {sanitize_text(remediation or finding.remediation, limit=MAX_REMEDIATION_FIELD)}",
        f"Frameworks supplied by AntiFine: {', '.join(sanitize_text(item, limit=300) for item in frameworks) or 'None supplied'}",
        f"BEFORE:\n{sanitize_text(before, limit=MAX_REMEDIATION_FIELD)}",
        f"AFTER:\n{sanitize_text(after, limit=MAX_REMEDIATION_FIELD)}",
        f"DETERMINISTIC DIFF:\n{sanitize_text(diff, limit=MAX_REMEDIATION_FIELD)}",
    ]
    prompt = "\n\n".join(sections)
    # Leave room for the truncation marker itself.
    return sanitize_text(prompt, limit=MAX_REMEDIATION_PROMPT - len("\n[TRUNCATED]"))
